name: ar_flutter_plugin_flutterflow
description: This plugin is a fork of the original AR Flutter Plugin, updated solely to modify the gradle parameters for compatibility with FlutterFlow.
version: 0.7.39
repository: https://github.com/hlefe/ar_flutter_plugin_flutterflow

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.1.0
  vector_math: ^2.1.1
  json_annotation: ^4.5.0
  geolocator: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: io.carius.lars.ar_flutter_plugin_flutterflow
        pluginClass: ArFlutterPlugin
      ios:
        pluginClass: ArFlutterPlugin
